### ISSUE TITLE
stuck loading on download

### ISSUE THREAD

**Issue by TheKfcBandit** [RiskiVR/BSLegacyLauncher#8] opened 2021-07-23 03:12 UTC
![image](https://user-images.githubusercontent.com/68492220/126733495-e212ef9b-f75f-45b3-8305-3393832df16e.png)

**Comment by UrkiMimi** [comment] 2021-07-23 03:15
Welp looks like a dupe of issue #1 again. Can you please read the open issues before opening one.

**Closed as completed** 2021-07-23 04:39 UTC
