### ISSUE TITLE
bs legacy launcher asks to install .NET 6.0, the website it sends you to dose not exist.

### ISSUE THREAD

**Issue by KiwiHuman** [RiskiVR/BSLegacyLauncher#60] opened 2023-07-30 17:06 UTC
when you try to download a new version and sign in to steam BS legacy launcher asks to install .NET 6.0, the website it sends you to (https://link.bslegacy.com/dotnet6) dose not exist. visiting  https://bslegacy.com/ shows that the owner of the domain seems to be [mintlilly](https://github.com/MintLily) and due to a falling out between the maintainers of the project necessary resources for the running of the program are no longer available and the website only shows a page containing the following image alongside a small amount of text that adds context to the image.
![picture shown on the BS legacy launcher website.](https://bslegacy.com/Screenshot_2023-06-09.png)

I request that if the current maintainers of this project cannot resolve the ongoing issues with https://bslegacy.com/ and [mintlilly](https://github.com/MintLily) then at least make the program functional again, either through changing domains or preferably linking to the official .NET download from Microsoft.

**Comment by KiwiHuman** [comment] 2023-07-30 17:08
downloading .NET 6.0 manually from the Microsoft website did not solve the issues in the launcher

**Comment by RiskiVR** [comment] 2023-07-30 20:39
Duplicate of #59

**Closed as completed by RiskiVR** 2023-07-30 20:39 UTC
